name: tbHCA
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.10
  - nextflow
  - pandas
  - psycopg2
  - pysam
  - biopython
  - fastp
  - bwa
  - minimap2
  - sambamba
  - samtools
  - umi_tools
  - numpy
  - openpyxl
  - multiqc
  - papermill
  - nbconvert
  - quilt3
  - bcftools
  - pigz
  - bedtools
  - picard=3.1.1
  - fgsv
  - fgbio
  - itables
  - pip:
    - benchling-sdk
    - ipykernel

